apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: sharepoint-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  spec:
    definition:
      title: sharepoint-source
      description: |-
        Fetches data from sharepoint
  dependencies:
    - "camel:core"
    - "camel:timer"
    - "camel:kamelet"
  template:
    from:
      uri: direct:sharepoint
      steps:
        - transform:
          -simple: “grant_type=client_credentials&client_id=${header.client-id}@${header.tenant-id}&client_secret=${header.client-secret}&resource=00000003-0000-0ff1-ce00-000000000000/neomsa.sharepoint.com@${header.tenant-id}”
        - setHeader:
          name: Content-Type
          constant: application/x-www-form-urlencoded
        - setHeader:
          name: Exchange.HTTP_PATH
          simple: “${header.tenant-id}/tokens/OAuth/2”
        - to:
          uri: https://accounts.accesscontrol.windows.net/
          parameters:
            bridgeEndpoint: true
            httpMethod: POST
            clearExpiredCookies: true
        - removeHeaders:
            pattern: CamelHttp*
        - transform:
            jsonpath: $.access_token
        - setHeader:
            name: Authorization
            simple: Bearer ${body}
        - setHeader:
            name: Exchange.HTTP_PATH
            simple: getbytitle('${header.title}')/items?$filter=${header.filter}
        - setHeader:
            name: Accept
            constant: application/json;odata= nometadata
        - setHeader:
            name: Content-Type
            constant: application/json;odata=verbose
        - to:
            uri: >-
              https://neomsa.sharepoint.com/sites/OXAGONWarehouseManagementSystem/_api/web/lists/
            parameters:
              bridgeEndpoint: true
              httpMethod: GET
              copyHeaders: true
              clearExpiredCookies: true