apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: sharepoint-sink
  annotations:
    camel.apache.org/kamelet.support.level: "Stable"
    camel.apache.org/catalog.version: "3.20.1.1"
    camel.apache.org/kamelet.icon: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MjAiCmhlaWdodD0iNDIwIiBzdHJva2U9IiMwMDAiIGZpbGw9Im5vbmUiPgo8cGF0aCBzdHJva2Utd2lkdGg9IjI2IgpkPSJNMjA5LDE1YTE5NSwxOTUgMCAxLDAgMiwweiIvPgo8cGF0aCBzdHJva2Utd2lkdGg9IjE4IgpkPSJtMjEwLDE1djM5MG0xOTUtMTk1SDE1TTU5LDkwYTI2MCwyNjAgMCAwLDAgMzAyLDAgbTAsMjQwIGEyNjAsMjYwIDAgMCwwLTMwMiwwTTE5NSwyMGEyNTAsMjUwIDAgMCwwIDAsMzgyIG0zMCwwIGEyNTAsMjUwIDAgMCwwIDAtMzgyIi8+Cjwvc3ZnPg=="
    camel.apache.org/provider: "Apache Software Foundation"
    camel.apache.org/kamelet.group: "HTTP"
  labels:
    camel.apache.org/kamelet.type: sink
spec:
  definition:
    title: sharepoint-sink
    description: Fetch data from Sharepoint endpoint.
    required:
    - authtokenurl
    - sharepointurl
    type: object
    properties:
      authtokenurl:
        title: Auth Token URL
        description: Auth Token service URL.
        type: string
        example: "https://my-service/path"
        pattern: "^(http|https)://.*"
      sharepointurl:
        title: Sharepoint URL
        description: Sharepoint URL.
        type: string
        example: "https://my-service/path"
        pattern: "^(http|https)://.*"
  dependencies:
  - "camel:http"
  - "camel:kamelet"
  - "camel:core"
  template:
    from:
      uri: kamelet:source
      steps:
      - remove-header:
          name: CamelHttpUri
      - transform:
          simple: grant_type=client_credentials&client_id=${header.client-id}@${header.tenant-id}&client_secret=${header.client-secret}&resource=00000003-0000-0ff1-ce00-000000000000/neomsa.sharepoint.com@${header.tenant-id}
      - set-header:
          name: CamelHttpMethod
          constant: POST
      - set-header:
          name: Content-Type
          constant: application/x-www-form-urlencoded
      - set-header:
          name: Exchange.HTTP_PATH
          simple: ${header.tenant-id}/tokens/OAuth/2
      - to: "{{authtokenurl}}"
        parameters: 
          bridgeEndpoint: true
          httpMethod: GET
          copyHeaders: true
          clearExpiredCookies: true
      - remove-header:
            name: CamelHttpUri
      - transform:
          jsonpath: $.access_token
      - set-header:
          name: Authorization
          simple: Bearer ${body}
      - set-header:
         name: Exchange.HTTP_PATH
         simple: getbytitle('${header.title}')/items?$filter=${header.filter}
      - set-header:
         name: Accept
         constant: application/json;odata= nometadata
      - set-header:
         name: Content-Type
         constant: application/json;odata=verbose
      - to: "{{sharepointurl}}"
        parameters: 
          bridgeEndpoint: true
          httpMethod: GET
          copyHeaders: true
          clearExpiredCookies: true