apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

resources:
- karavan-quarkus-task-minikube.yaml
- karavan-app-service-node-port.yaml
- pipeline-service-account.yaml
- karavan-app-ingress.yaml