kind: Secret
apiVersion: v1
metadata:
  name: karavan
type: Opaque
stringData:
  master-password: karavan
  oidc-secret: XXXXX
  oidc-server-url: https://localhost/auth/realms/karavan
  oidc-frontend-url: https://localhost/auth
  projects-git-repository: http://karavan-repo.karavan.svc.cluster.local/karavan1/projects.git
  projects-git-password: karavan
  projects-git-username: karavan1
  projects-git-branch: main
  kamelets-git-repository: http://karavan-repo.karavan.svc.cluster.local/karavan2/kamelets.git
  kamelets-git-password: karavan
  kamelets-git-username: karavan2
  kamelets-git-branch: main
  image-registry: image-registry.openshift-image-registry.svc:5000
