name: cloud-native app 

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #  Generate Karavan UI model and API, Kamelets and Components
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/camel/karavan
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Generate Karavan UI model and API, Kamelets and Components
        run: |
          mvn clean compile exec:java -f karavan-generator \
          -Dexec.mainClass="org.apache.camel.karavan.generator.KaravanGenerator"

      #  Building Karavan Core
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Karavan Core install
        working-directory: ./karavan-core
        run: npm install

      #  Build Karavan cloud app with public access
      - name: Build application public
        run: |
          mvn package -f karavan-app -Dquarkus.profile=public -DskipTest \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.image=ghcr.io/${GITHUB_REPOSITORY}:3.18.3 \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}

      #  Build Karavan cloud app with basic authorization
      - name: Build application basic auth
        run: |
          mvn package -f karavan-app -Dquarkus.profile=basic -DskipTest \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.image=ghcr.io/${GITHUB_REPOSITORY}-basic:3.18.3 \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}

      #  Build Karavan cloud app with oidc authorization
      - name: Build application oidc
        run: |
          mvn package -f karavan-app -Dquarkus.profile=oidc -DskipTest \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.image=ghcr.io/${GITHUB_REPOSITORY}-oidc:3.18.3 \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}